# Generated by Django 4.1.7 on 2023-02-22 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='owner_documets')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='land_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('photo1', models.ImageField(upload_to='land')),
                ('photo2', models.ImageField(upload_to='land')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.owner')),
            ],
        ),
        migrations.CreateModel(
            name='house_and_appartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('bedroom', models.CharField(max_length=100)),
                ('bathroom', models.CharField(max_length=100)),
                ('furnished', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('photo1', models.ImageField(upload_to='house')),
                ('photo2', models.ImageField(upload_to='house')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.house_and_appartments')),
                ('land', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.land_property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
